std_msgs/Header header

# Linear velocity command [m/s]. Positive values indicate forward motion,
# negative values indicate reverse motion.
float32 velocity

# Desired curvature (reciprocal of radius of turning) of motion. A curvature
# of 0 indicates an infinite radius of turning, corresponding to linear
# motion. Positive values of curvature indicate turning to the left, negative
# values indicate turning to the right.
float32 curvature
