#!/bin/bash
sudo apt install libpopt-dev libgoogle-perftools-dev
UBUNTU_VERSION=`lsb_release -rs`
UBUNTU_OLDER_THAN_TRUSTY=`echo ${UBUNTU_VERSION}"<14.04" | bc`
if [[ $UBUNTU_OLDER_THAN_TRUSTY -eq 1 ]];
then
    pushd src/libraries/google-glog && ./configure && make -j`nproc` && \
	sudo make -j`nproc` install || \
	{ echo 'Error: glog failed' >&2; exit 1; }
    popd
    pushd src/libraries/gflags && ./configure && make -j`nproc` && \
	sudo make -j`nproc` install || \
	{ echo 'Error: gflags failed' >&2; exit 1; }
    popd
else
    sudo apt-get install libgoogle-glog-dev libgflags-dev || \
	{ echo 'Error: glog and gflags installation failed' >&2; exit 1; }
fi
